//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltorsAPP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public string Passport { get; set; }
        public int Document_for_housing { get; set; }
        public string Mail { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
